name: Benchmark

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: 'codspeed-macro'
    name: Benchmark

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"

#      - name: Apt
#        run: sudo apt-get -q update && sudo apt-get -y install $(cat .github/linux_apt_dependencies.txt)

      - name: Install core Python packages
        run: python -m pip install --upgrade -r requirements-setuptools.txt

      - name: Install Python packages
        run: python -m pip install -c requirements.txt -e ".[server,test]"

      - name: run pytest (benchmark)
        uses: CodSpeedHQ/action@v3
        with:
          run: python -m pytest --skip-gui-tests -p no:pytest-qt --continue-on-collection-errors --ignore-glob='**/gui' --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
