name: Benchmark

on:
  pull_request:
  push:
    branches:
      - main
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:


jobs:
  benchmark:
    runs-on: 'ubuntu-latest'
    name: Benchmark

    timeout-minutes: 30
    strategy:
      matrix:
        shard: [1,2,3,4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"

      - name: Apt
        run: sudo apt-get -q update && sudo apt-get -y install $(cat .github/linux_apt_dependencies.txt)

      - name: Install core Python packages
        run: python -m pip install --upgrade -r requirements-setuptools.txt

      - name: Install Python packages
        run: python -m pip install -r requirements.txt -e ".[exporters,server,test]"

      - name: build ui files
        run: python setup.py build_ui

      - name: run pytest (benchmark)
        uses: CodSpeedHQ/action@v3
        with:
          run: python -m pytest --skip-gui-tests --test-group=${{ matrix.shard }} --test-group-count=4 --codspeed --codspeed-mode=walltime
          token: ${{ secrets.CODSPEED_TOKEN }}
